# 工作流
name: FastAPI CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  test:

    runs-on: ubuntu-latest

    steps:

      # 拉取代码
      - name: Checkout Code
        uses: actions/checkout@v4

      # 安装python
      - name: Setup Python
        uses: actions/setup-python@v5

        with:
          python-version: "3.11"

      # 安装依赖
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      # 执行测试
      - name: Run Tests
        run: |
          pytest